apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 07-crossplane
  namespace: argocd
spec:
  destination:
    namespace: demonstration-crossplane
    server: https://kubernetes.default.svc
  project: container-talk
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 2.2.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true